#!/usr/bin/bash

# Unless stated otherwise
#  - the searches must be case insensitive
#  - All .txt and .csv files must be searched
#
# Each problem describes what you are searching for, it is your task to
# write a grep command that will find them.
#
# The correct number of found items is listed to help you know if you have
# the right answer.  You can use a pipe and the wc command to count the
# number of lines returned by grep.

# SAMPLE
# Use the grep command to find the word 'TIME' in any .txt or .csv file in
# the current directory. Case does not matter.
#
# -E uses extended syntax (not needed here)
# -i case-insensitive search
# -w whole word only ('sometimes' won't match)
# grep -Eiw TIME *.txt *.csv | wc -l

# PROBLEM 1 (59 found)
# Find all years from 1900-1999
echo "PROBLEM 1"
echo "Existing: 59"
echo -n "Found: "
grep "19"[0-9][0-9] *.txt *csv | wc -l

# PROBLEM 2 (103 found)
# Find all years from 1900-2099
echo -e "\nPROBLEM 2"
echo "Existing: 103"
echo -n "Found: "
grep -E '\<(19|20)[0-9][0-9]\>' *.txt *csv | wc -l

# PROBLEM 3 (70 found)
# With out using the w option, find all instances of the word old
echo -e "\nPROBLEM 3"
echo "Existing: 72"
echo -n "Found: "
grep -i '\<old\>' *.txt *csv | wc -l

# PROBLEM 4 (17 found)
# Anything that looks like a letter grade inside of double quotes
# Uppercase letters only and may or may not have a + op - following it
echo -e "\nPROBLEM 4"
echo "Existing: 16"
echo -n "Found: "
grep -E '"[ABCDF][+-]?"' *.txt *csv | wc -l

# PROBLEM 5 (16 found)
# All words that begin with a vowel and end with 'it' in wordlist.txt
echo -e "\nPROBLEM 5"
echo "Existing: 16"
echo -n "Found: "
grep -E -i ^[aeiou][[:alpha:]]+"it"$ wordlist.txt | wc -l

# PROBLEM 6 (6 found)
# All in wordlist.txt words that do not begin with a vowel but end with
# 'es' and are at least 7 characters in length
echo -e "\nPROBLEM 6"
echo "Existing: 6"
echo -n "Found: "
grep -E '^[^aeiou][[:alpha:]]{4,}es$' wordlist.txt | wc -l

# PROBLEM 7 (30 found)
# Find all dollar amounts with optional cents
# ($ followed by digits with one possible .)
echo -e "\nPROBLEM 7"
echo "Existing: 30"
echo -n "Found: "
grep -E '\$[[:digit:]]+(\.[[:digit:]]+)?' *.txt *csv | wc -l
