//*********************************************************
// filename: lex.h
// purpose: Defines global symbols used the the flex 
//          generated lexer and bison generated parser.
// author: Rowan Parker (rowan.parker@oit.edu)
// date: 01/19/2019

#pragma once

#include "cAstNode.h"
#include "cSymbolTable.h"

// parse function generated by bison
int yyparse();

// lexer function generated by flex
int yylex();

// text of the current token
extern char *yytext;        

// line number of current token
extern int yylineno;        

// num of compile errors
extern int yynerrs;

// FILE pointer for input
extern FILE *yyin;          

// root of AST
extern cAstNode *yyast_root;
